version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf #日本語対応
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    platform: linux/x86_64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: [ "8888:80" ]
    depends_on: [ "db" ]
    environment:
      MEMORY_LIMIT: 3G
      UPLOAD_LIMIT: 3G

  php:
    image: php:7.4-fpm
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: [ "db" ]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports: [ "8080:80" ]
    depends_on: [ "php", "python" ]

  httpd:
    image: php:7.4-apache
    ports: ["8889:80"]
    volumes:
      - ./htdocs:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: [ "db" ]

  python:
    image: python:3.12
    volumes:
      - ./python-app:/app
    working_dir: /app
    command: >
      bash -c "pip install Flask requests && python read_web.py"
    restart: always
    environment:
      DISPLAY: host.docker.internal:0.0

